version: "3"

services:
  fuel-app:
    build:
      context: .
      dockerfile: ./docker/fuel-app/Dockerfile
    volumes:
      - ./docker/fuel-app/php.ini:/usr/local/etc/php/php.ini
      - ./fuel-app:/var/www
    working_dir: /var/www
    ports:
      - "8080:8080"
    command: "php -S 0.0.0.0:8080 -t public"
