version: "3"

services:
  fuel-app:
    build:
      context: .
      dockerfile: ./docker/fuel-app/Dockerfile
    volumes:
      - ./docker/fuel-app/php.ini:/usr/local/etc/php/php.ini
      - ./fuel-app:/var/www
    working_dir: /var/www
    ports:
      - "8080:8080"
    command: "php -S 0.0.0.0:8080 -t public"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fuel_db
      MYSQL_USER: fuel
      MYSQL_PASSWORD: fuel_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
